# Generated by Django 5.1.4 on 2025-01-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.TextField()),
                ('preferred_term', models.DurationField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('publish_status', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='loan_documents/')),
                ('is_terms_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
