# Generated by Django 5.1.4 on 2025-01-28 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_offered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirements', models.TextField(blank=True)),
                ('terms_conditions', models.TextField()),
                ('is_terms_accepted', models.BooleanField(default=False)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lending_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
