# Generated by Django 5.1.4 on 2025-01-28 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MODIFIED', 'Modified'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted')], max_length=20)),
                ('borrower_consent', models.BooleanField(default=False)),
                ('lender_consent', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('receipt', models.FileField(null=True, upload_to='receipts/')),
                ('contract_doc', models.FileField(null=True, upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests_as_borrower', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests_as_lender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['borrower', 'status'], name='transaction_borrowe_c0264b_idx'), models.Index(fields=['lender', 'status'], name='transaction_lender__b4c23f_idx')],
            },
        ),
    ]
