# Generated by Django 5.1.4 on 2025-01-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loanrequest',
            new_name='transaction_borrowe_c0264b_idx',
            old_name='MoneyAPi_lo_borrowe_64ab45_idx',
        ),
        migrations.RenameIndex(
            model_name='loanrequest',
            new_name='transaction_lender__b4c23f_idx',
            old_name='MoneyAPi_lo_lender__a41644_idx',
        ),
    ]
